
TOP=../..
.include "$(TOP)/mk/os161.config.mk"

# Just add new directories at the end of the line below.
SUBDIRS= example writeConsole	timeofDay getpid stubtest fork

.include "$(TOP)/mk/os161.subdir.mk"
